#!/bin/bash
export ETCD_NAME="infra0"
export ETCD_INITIAL_CLUSTER="infra0=http://10.3.6.90:2380,infra1=http://10.3.8.62:2380,infra2=http://10.3.8.63:2380"
export ETCD_INITIAL_CLUSTER_STATE=existing
export ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.3.8.63:2380"
export ETCD_LISTEN_PEER_URLS="http://10.3.8.63:2380"
export ETCD_LISTEN_CLIENT_URLS="http://10.3.8.63:2379,http://127.0.0.1:2379"
export ETCD_ADVERTISE_CLIENT_URLS="http://10.3.8.63:2379"
